---

- hosts: s3
  become: yes
  gather_facts: no
  roles:
    - role: 'roles/setup-s3'
    - role: 'roles/configure-s3'


- hosts: lb
  become: yes
  gather_facts: yes
  roles:
    - role: 'roles/setup-lb'
    - role: 'roles/configure-lb'
