---

- hosts: s3
  become: yes
  gather_facts: no
  roles:
    - role: 'roles/setup-s3'
      when: s3 is defined



- hosts: lb
  become: yes
  gather_facts: yes
  roles:
    - role: 'roles/setup-lb'
      when: lb is defined
