---

all:
  vars:
    ansible_user: vagrant
    ports:
      - 9000
      - 9001
    minio:
      domain: "minio.example.com"
      network_prefix: "192.168.150.10"
      first_host: 1
      last_host: 6
      server:
        url: "https://dl.min.io/server/minio/release/linux-amd64/minio.RELEASE.2019-10-12T01-39-57Z"
        sum: "sha256:42afc5da93e28341fd11a6491b57800fbfc53210ad156a2330afb09c9d71644f"
        binary: /usr/local/bin/minio_server
        workdir: /var/lib/minio
        confdir: /etc/minio
        user: minio
      client:
        url: "https://dl.min.io/client/mc/release/linux-amd64/mc.RELEASE.2019-10-09T22-54-57Z"
        sum: "sha256:e32d5ca6ec9ddcb5d4a28c1a00b78e76513883f2b0e8637435c5c0a42dc8697b"
        binary: /usr/local/bin/minio_client
      tenants:
        one:
          name: one
          port: 9000
          datadir: /srv/minio/one
          config: "/etc/default/minio-one"
          enabled: yes
          access_key: PuX9demtWb3
          secret_key: wHgrszE9iEj
        two:
          name: two
          port: 9001
          datadir: /srv/minio/two
          config: "/etc/default/minio-two"
          enabled: yes
          access_key: EwNdTteymL7
          secret_key: dmh3sUf4qbN

s3:
  hosts:
    192.168.150.101:
    192.168.150.102:
    192.168.150.103:
    192.168.150.104:
    192.168.150.105:
    192.168.150.106:

lb:
  vars:
    nginx:
      status_socket: "127.0.0.1:88"
      status_allow_from:
        - "127.0.0.1"
    keepalived:
      nginx_status:
        interval: 5
        timeout: 5
        rise: 2
        fall: 2
      vrrp_instances:
        a:
          name: a
          virtual_router_id: 31
          virtual_ipaddress: 192.168.150.31
          auth_pass: qwe123
          interface: enp0s8
        b:
          name: b
          virtual_router_id: 32
          virtual_ipaddress: 192.168.150.32
          auth_pass: asd123
          interface: enp0s8
        c:
          name: c
          virtual_router_id: 33
          virtual_ipaddress: 192.168.150.33
          auth_pass: zxc123
          interface: enp0s8


  hosts:
    192.168.150.201:
      keepalived_host:
        vrrp_instances:
          a:
            name: a
            priority: 150
          b:
            name: b
            priority: 100
          c:
            name: c
            priority: 50

    192.168.150.202:
      keepalived_host:
        vrrp_instances:
          a:
            name: a
            priority: 100
          b:
            name: b
            priority: 150
          c:
            name: c
            priority: 100

    192.168.150.203:
      keepalived_host:
        vrrp_instances:
          a:
            name: a
            priority: 50
          b:
            name: b
            priority: 50
          c:
            name: c
            priority: 150
