---

all:
  vars:
    ansible_user: vagrant
    ports:
      - 9000
      - 9001
    minio:
      domain: "minio.example.com"
      url: "https://dl.min.io/server/minio/release/linux-amd64/minio.RELEASE.2019-10-12T01-39-57Z"
      sum: "sha256:42afc5da93e28341fd11a6491b57800fbfc53210ad156a2330afb09c9d71644f"
      binary: /usr/local/bin/minio
      workdir: /var/lib/minio
      user: minio
      tenants:
        one:
          name: one
          port: 9000
          datadir: /srv/minio/one
          config: "/etc/default/minio-one"
          enabled: yes
        two:
          name: two
          port: 9001
          datadir: /srv/minio/two
          config: "/etc/default/minio-two"
          enabled: yes

s3:
  hosts:
    192.168.150.11:
    192.168.150.12:
    192.168.150.13:
    192.168.150.14:
    192.168.150.15:
    192.168.150.16:

lb:
  vars:
    nginx:
      status_socket: "127.0.0.1:88"
      status_allow_from:
        - "127.0.0.1"
    keepalived:
      vrrp_instances:
        a:
          name: a
          virtual_router_id: 31
          virtual_ipaddress: 192.168.150.31
          auth_pass: qwe123
        b:
          name: b
          virtual_router_id: 32
          virtual_ipaddress: 192.168.150.32
          auth_pass: asd123
        c:
          name: c
          virtual_router_id: 33
          virtual_ipaddress: 192.168.150.33
          auth_pass: zxc123


  hosts:
    192.168.150.21:
    192.168.150.22:
    192.168.150.23:
