---

all:
  vars:
    ansible_user: vagrant
    minio:
      url: "https://dl.min.io/server/minio/release/linux-amd64/minio.RELEASE.2019-10-12T01-39-57Z"
      sum: "sha256:42afc5da93e28341fd11a6491b57800fbfc53210ad156a2330afb09c9d71644f"
      binary: /usr/local/bin/minio
      workdir: /var/lib/minio
      user: minio
      tenants:
        one:
          name: one
          port: 9000
          datadir: /srv/minio/one
          config: "/etc/default/minio-one"
          enabled: yes
        two:
          name: two
          port: 9001
          datadir: /srv/minio/two
          config: "/etc/default/minio-two"
          enabled: yes


minio:
  hosts:
    192.168.150.11:
    192.168.150.12:
    192.168.150.13:
    192.168.150.14:
    192.168.150.15:
    192.168.150.16:
