---

- ping:


- name: generate tenant configuration file
  template:
    dest: "/etc/default/minio-{{ item.value.name }}"
    src: "minio.default.j2"
    owner: root
    group: root
    mode: '0640'
  with_dict: "{{ minio.tenants }}"
  notify: "restart minio"


- name: generate tenant service file
  template:
    dest: "/etc/systemd/system/minio-{{ item.value.name }}.service"
    src: "minio.service.j2"
    owner: root
    group: root
    mode: '0640'
  with_dict: "{{ minio.tenants }}"
  notify: "restart minio"
